# Generated by Django 4.1 on 2022-11-20 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_num', models.CharField(max_length=15, unique=True)),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_desc', models.TextField(max_length=500)),
                ('pet_image', models.ImageField(blank=True, default=pets.models.get_default_profile_image, max_length=255, null=True, upload_to=pets.models.get_profile_image_filepath)),
                ('is_lost', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
