# Generated by Django 4.1 on 2022-12-03 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_num', models.CharField(max_length=15, unique=True, verbose_name='numer chipu')),
                ('pet_name', models.CharField(max_length=30, verbose_name='imię zwierzęcia')),
                ('pet_desc', models.TextField(max_length=500, verbose_name='opis zwierzęcia')),
                ('pet_image', models.ImageField(blank=True, default=pets.models.get_default_profile_image, max_length=255, null=True, upload_to=pets.models.get_profile_image_filepath, verbose_name='zdjęcie')),
                ('is_lost', models.BooleanField(default=False, verbose_name='status zaginięcia')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='data dodania')),
                ('owner', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='właściciel zwierzęcia')),
            ],
        ),
    ]
