# Generated by Django 4.1 on 2022-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='pet_sex',
            field=models.CharField(choices=[('-----', '-----'), ('Samiec', 'Samiec'), ('Samica', 'Samica')], default='-----', max_length=13, verbose_name='płeć'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='pet_type',
            field=models.CharField(choices=[('-----', '-----'), ('Gryzoń', 'Gryzoń'), ('Gad', 'Gad'), ('Kot', 'Kot'), ('Pies', 'Pies'), ('Ptak', 'Ptak'), ('Inny', 'Inny')], default='-----', max_length=6, verbose_name='Gatunek'),
        ),
    ]
