# Generated by Django 4.1 on 2022-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petprofile_pet_sex_petprofile_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_sex',
            field=models.CharField(choices=[('-----', '-----'), ('Samiec', 'Samiec <i class="fas fa-mars"></i>'), ('Samica', 'Samica <i class="fas fa-venus"></i>')], default='-----', max_length=13, verbose_name='płeć'),
        ),
    ]
