# Generated by Django 4.1 on 2022-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petprofile_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_sex',
            field=models.CharField(choices=[('-----', '-----'), ('Samiec', 'Samiec'), ('Samica', 'Samica')], default='-----', max_length=13, verbose_name='płeć'),
        ),
    ]
