# Generated by Django 4.1 on 2022-12-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petprofile_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_sex',
            field=models.CharField(choices=[('Samiec', 'Samiec'), ('Samica', 'Samica')], default='Samiec', max_length=13, verbose_name='płeć'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_type',
            field=models.CharField(choices=[('Gryzoń', 'Gryzoń'), ('Gad', 'Gad'), ('Kot', 'Kot'), ('Pies', 'Pies'), ('Ptak', 'Ptak'), ('Inny', 'Inny')], default='Gryzoń', max_length=6, verbose_name='Gatunek'),
        ),
    ]
