# Generated by Django 4.1 on 2022-09-11 17:25

import app.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=65, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pet_num', models.CharField(max_length=15, unique=True)),
                ('pet_name', models.CharField(max_length=30, unique=True)),
                ('pet_desc', models.TextField(max_length=500)),
                ('pet_image', models.ImageField(blank=True, default=app.models.get_default_profile_image, max_length=255, null=True, upload_to=app.models.get_profile_image_filepath)),
                ('is_lost', models.BooleanField(default=False)),
            ],
        ),
    ]
