# Generated by Django 4.1 on 2022-09-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
