# Generated by Django 4.1 on 2022-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pet_desc',
            field=models.TextField(),
        ),
    ]
