# Generated by Django 4.1 on 2022-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pet_name',
            field=models.CharField(max_length=30),
        ),
    ]
