# Generated by Django 4.1 on 2022-09-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_pet_desc_alter_profile_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pet_image',
        ),
    ]
