# Generated by Django 4.1 on 2022-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_profile_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pet_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
