# Generated by Django 4.1 on 2022-11-13 10:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Aktywność konta użytkownika', verbose_name='konto aktywne'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Możliwość zalogowania do panelu administracyjnego', verbose_name='administrator'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(help_text='Użytkownik ma pełną kontrolę bez delegacji uprawnień', verbose_name='status SuperUsera'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='ostatnie logowanie'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='numer telefonu'),
        ),
    ]
