# Generated by Django 4.1 on 2022-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_active_alter_account_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Użytkownik ma pełną kontrolę bez delegacji uprawnień', verbose_name='status SuperUsera'),
        ),
    ]
