# Generated by Django 4.1 on 2022-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(choices=[('Inna lokalizacja', 'Inna lokalizacja'), ('Dolnośląskie', 'Dolnośląskie'), ('Kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Łódzkie', 'Łódzkie'), ('Małopolskie', 'Małopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Śląskie', 'Śląskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Warmińsko-mazurskie', 'Warmińsko-mazurskie'), ('Zachodnio-pomorskie', 'Zachodnio-pomorskie')], default='Inna lokalizacja', max_length=19, verbose_name='województwo'),
        ),
    ]
